# ruff configuration file
target-version = "py39"
line-length = 120
exclude = [
  ".git,",
  "__pycache__",
  "build",
]

[lint]
select = ["E", "F", "W", "UP", "PT"]
extend-ignore = [
  # pycodestyle (E, W)
  "E501", # LineTooLong
  # pytest (PT)
  "PT001", # Always use pytest.fixture()
  "PT004", # Fixtures which don't return anything should have leading _
  "PT007", # Parametrize should be lists of tuples
  "PT011", # Too broad exception assert
  "PT023", # Always use () on pytest decorators
]


[lint.per-file-ignores]

[lint.pydocstyle]
convention = "numpy"
